filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/myapp/*.log
    encoding: utf-8

    ignore_older: 0
    scan_frequency: 10s
    close_inactive: 5m
    clean_inactive: 0s

    fields:
      server_name: file-beat-server
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5001"]
